#include "ble_findmy.h"
#include "../toolkit_log.h"
#include "../toolkit_ui.h"

#include <furi.h>
#include <furi_hal_bt.h>
#include <furi_hal_rtc.h>
#include <extra_beacon.h>
#include <gui/view.h>

// OpenHaystack public key length for SECP224R1 is 28 bytes (the two points
// packed without the 0x02/0x03 prefix, because Find My prepends the header).
#define BLE_FINDMY_KEY_LEN (28)

// The real OpenHaystack advertisement payload is 28 bytes of SECP224R1 public
// key data that Apple devices scan for and report to iCloud. Replace this
// placeholder with your own key generated by the OpenHaystack macOS app or
// the flipper companion app.
static const uint8_t ble_findmy_key[BLE_FINDMY_KEY_LEN] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
    0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f,
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17,
    0x18, 0x19, 0x1a, 0x1b,
};

#define BLE_FINDMY_REFRESH_EVENT 0u
#define BLE_FINDMY_REFRESH_MS    500

typedef struct {
    View* view;
    FuriTimer* refresh_timer;
    bool beacon_active;
} BleFindMyCtx;

/* --------------------------------- draw ------------------------------------ */

static void ble_findmy_draw_callback(Canvas* canvas, void* model) {
    BleFindMyCtx* ctx = model;
    canvas_clear(canvas);
    toolkit_ui_draw_title_bar(canvas, "BLE Find My");

    char line[40];

    // Show the public key as two hex blocks to fit the 128 px screen.
    snprintf(line, sizeof(line), "Key: %02x%02x%02x%02x%02x%02x%02x%02x",
        ble_findmy_key[0], ble_findmy_key[1], ble_findmy_key[2], ble_findmy_key[3],
        ble_findmy_key[4], ble_findmy_key[5], ble_findmy_key[6], ble_findmy_key[7]);
    canvas_draw_str(canvas, 4, 24, line);

    snprintf(line, sizeof(line), "     %02x%02x%02x%02x%02x%02x%02x%02x",
        ble_findmy_key[8], ble_findmy_key[9], ble_findmy_key[10], ble_findmy_key[11],
        ble_findmy_key[12], ble_findmy_key[13], ble_findmy_key[14], ble_findmy_key[15]);
    canvas_draw_str(canvas, 4, 35, line);

    snprintf(line, sizeof(line), "     %02x%02x%02x%02x%02x%02x%02x%02x",
        ble_findmy_key[16], ble_findmy_key[17], ble_findmy_key[18], ble_findmy_key[19],
        ble_findmy_key[20], ble_findmy_key[21], ble_findmy_key[22], ble_findmy_key[23]);
    canvas_draw_str(canvas, 4, 46, line);

    snprintf(line, sizeof(line), "Beacon: %s", ctx->beacon_active ? "ON" : "OFF");
    canvas_draw_str(canvas, 4, 57, line);

    canvas_draw_str(canvas, 4, 63, "Back: exit module");
}

/* -------------------------------- timer ------------------------------------ */

static void ble_findmy_timer_callback(void* context) {
    ToolkitApp* app = context;
    view_dispatcher_send_custom_event(
        app->view_dispatcher, EVENT_MAKE(BLE_FINDMY_REFRESH_EVENT, app->gen));
}

/* ------------------------------- lifecycle ---------------------------------- */

void ble_findmy_enter(ToolkitApp* app) {
    BleFindMyCtx* ctx = malloc(sizeof(BleFindMyCtx));
    ctx->beacon_active = furi_hal_bt_extra_beacon_is_active();
    app->active_ctx = ctx;

    ctx->view = view_alloc();
    view_set_draw_callback(ctx->view, ble_findmy_draw_callback);
    view_allocate_model(ctx->view, ViewModelTypeLocking, sizeof(BleFindMyCtx));
    view_dispatcher_add_view(app->view_dispatcher, TOOLKIT_VIEW_BASE_BLE_FINDMY, ctx->view);

    // Core2 must be running the BLE stack for the extra beacon APIs to work.
    furi_hal_bt_ensure_c2_mode(BleGlueC2ModeStack);

    // Configure and start the extra beacon only if it is not already
    // running. The exit callback deliberately leaves the beacon active
    // (persistence is the feature), so re-entering the module must not
    // call start() on an already-running beacon — that triggers a
    // furi_check in the firmware.
    if(!furi_hal_bt_extra_beacon_is_active()) {
        GapExtraBeaconConfig config = {
            .min_adv_interval_ms = 2000,
            .max_adv_interval_ms = 2000,
            .adv_channel_map = GapAdvChannelMapAll,
            .adv_power_level = GapAdvPowerLevel_0dBm,
            .address_type = GapAddressTypeRandom,
            .address = {0x01, 0x02, 0x03, 0x04, 0x05, 0x06},
        };
        furi_hal_bt_extra_beacon_set_config(&config);
        furi_hal_bt_extra_beacon_set_data(ble_findmy_key, BLE_FINDMY_KEY_LEN);
        furi_hal_bt_extra_beacon_start();
    }

    ctx->refresh_timer = furi_timer_alloc(ble_findmy_timer_callback, FuriTimerTypePeriodic, app);
    furi_timer_start(ctx->refresh_timer, furi_ms_to_ticks(BLE_FINDMY_REFRESH_MS));

    view_dispatcher_switch_to_view(app->view_dispatcher, TOOLKIT_VIEW_BASE_BLE_FINDMY);

    ToolkitLogRecord rec = {.ts = furi_hal_rtc_get_timestamp(), .subsys = ToolkitSubsysBle};
    snprintf(rec.summary, sizeof(rec.summary), "ble findmy beacon started");
    rec.file[0] = '\0';
    toolkit_log_append(app, &rec);
}

void ble_findmy_exit(ToolkitApp* app) {
    BleFindMyCtx* ctx = app->active_ctx;

    furi_timer_stop(ctx->refresh_timer);
    furi_timer_free(ctx->refresh_timer);

    // Lifecycle deviation: intentionally do NOT stop the extra beacon. The
    // beacon runs on Core2 independently of this FAP; stopping it here would
    // defeat the purpose of remaining discoverable by Apple's Find My network
    // after leaving the module. The user must power-cycle to disable it.

    view_dispatcher_remove_view(app->view_dispatcher, TOOLKIT_VIEW_BASE_BLE_FINDMY);
    view_free(ctx->view);
    free(ctx);
    app->active_ctx = NULL;
}

bool ble_findmy_event(ToolkitApp* app, uint32_t id) {
    if(id != BLE_FINDMY_REFRESH_EVENT) return false;
    BleFindMyCtx* ctx = app->active_ctx;

    ctx->beacon_active = furi_hal_bt_extra_beacon_is_active();

    with_view_model(ctx->view, BleFindMyCtx * m, { *m = *ctx; }, true);
    return true;
}

bool ble_findmy_nav(ToolkitApp* app) {
    toolkit_exit_module(app);
    return true;
}
